/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://yuocdulx4rcujpb2jox6izolcm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2k3ufdkynnfs3adzhjmjuv2ur4",
    "aws_cognito_identity_pool_id": "us-east-1:a8d3cdc9-757f-48fc-8ab4-6bbfbf620799",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Sq75sH6VC",
    "aws_user_pools_web_client_id": "5hisgb75d904nlk73inr70n6ur",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplify-truckerapp-dev-133129-deployment",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
